# Generated by Django 2.0 on 2018-01-05 21:10

import Railapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seat_status',
            fields=[
                ('booked_seat_number', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='station',
            fields=[
                ('station_id', models.AutoField(max_length=120, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=120)),
                ('station_city', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr_no', models.CharField(default=Railapp.models.ticket.gen_pnr_no, editable=False, max_length=10, unique=True)),
                ('boarding_station', models.CharField(max_length=120, null=True)),
                ('destination', models.CharField(max_length=120, null=True)),
                ('fare', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='train_database',
            fields=[
                ('train_number', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=120)),
                ('origination', models.CharField(max_length=120, null=True)),
                ('destination', models.CharField(max_length=120, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='train_details',
            fields=[
                ('train_sno', models.AutoField(max_length=120, primary_key=True, serialize=False)),
                ('general_seats', models.CharField(max_length=120, null=True)),
                ('ac_seats', models.CharField(max_length=120, null=True)),
                ('general_fair', models.CharField(max_length=120, null=True)),
                ('ac_fair', models.CharField(max_length=120, null=True)),
                ('qouta_ladies', models.CharField(max_length=120)),
                ('qouta_general', models.CharField(max_length=120)),
                ('availability_days', models.CharField(max_length=120, null=True)),
                ('arrival_time', models.TimeField(default='20:00')),
                ('departure_time', models.TimeField(default='23:00')),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Railapp.station')),
                ('train_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Railapp.train_database')),
            ],
        ),
        migrations.CreateModel(
            name='user_database',
            fields=[
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email_id', models.EmailField(max_length=120, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=120)),
                ('gender', models.CharField(max_length=120)),
                ('martial_status', models.CharField(max_length=120)),
                ('dob', models.CharField(max_length=120)),
                ('mobile_no', models.CharField(max_length=120)),
                ('sec_question', models.CharField(max_length=120)),
                ('sec_ans', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Railapp.user_database'),
        ),
        migrations.AddField(
            model_name='seat_status',
            name='ticket_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Railapp.ticket'),
        ),
        migrations.AddField(
            model_name='seat_status',
            name='train_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Railapp.train_details'),
        ),
    ]
