# Generated by Django 2.0 on 2018-01-06 10:12

import Railapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railapp', '0002_auto_20180106_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='id',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pnr_no',
            field=models.CharField(default=Railapp.models.ticket.gen_pnr_no, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
