# Generated by Django 2.0 on 2018-01-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railapp', '0003_auto_20180106_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat_status',
            name='passenger_age',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='seat_status',
            name='passenger_sex',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
