# Generated by Django 2.0 on 2018-01-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Railapp', '0004_auto_20180106_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train_details',
            old_name='ac_fair',
            new_name='ac_fare',
        ),
        migrations.RenameField(
            model_name='train_details',
            old_name='general_fair',
            new_name='general_fare',
        ),
    ]
