# Generated by Django 2.0 on 2018-01-08 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Railapp', '0005_auto_20180106_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='train_week_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(max_length=120, null=True)),
                ('tuesday', models.CharField(max_length=120, null=True)),
                ('wednesday', models.CharField(max_length=120, null=True)),
                ('thursday', models.CharField(max_length=120, null=True)),
                ('friday', models.CharField(max_length=120, null=True)),
                ('saturday', models.CharField(max_length=120, null=True)),
                ('sunday', models.CharField(max_length=120, null=True)),
                ('train_number', models.ForeignKey(max_length=120, on_delete=django.db.models.deletion.CASCADE, to='Railapp.train_database')),
            ],
        ),
        migrations.AlterField(
            model_name='user_database',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
