# Generated by Django 2.0 on 2018-01-08 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Railapp', '0007_auto_20180109_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train_week_schedule',
            name='id',
        ),
        migrations.AlterField(
            model_name='train_week_schedule',
            name='train_number',
            field=models.ForeignKey(max_length=120, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Railapp.train_database'),
        ),
    ]
