# Generated by Django 2.0 on 2018-01-09 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Railapp', '0008_auto_20180109_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_week_schedule',
            name='train_number',
            field=models.OneToOneField(max_length=120, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Railapp.train_database'),
        ),
    ]
