# Generated by Django 2.0 on 2018-01-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railapp', '0009_auto_20180109_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='coach',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='doj',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
